name: up texture pack ğŸ“¤
on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  texturepack1_19_3:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checking branch 1.19.3ğŸ”ï¸
        uses: actions/checkout@v3

      - name: Redeem the sent Tag ğŸ·ï¸
        run: |
          TAG=$(git describe --tags --abbrev=0)
          TAG="${TAG#v}"
          echo "LATEST_TAG=$TAG" >> $GITHUB_ENV

      - name: Compressing texture from version 1.19.3ğŸ“¦ï¸
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.19.3.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Uploading the Texture 1.19.3ğŸ—ƒï¸
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          tag: "v${{ env.LATEST_TAG }}"
          name: "Dark Everywhere ${{ env.LATEST_TAG }}ğŸŒ™"
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

  texturepack1_19:
    needs: texturepack1_19_3
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checking branch 1.19ğŸ”ï¸
        uses: actions/checkout@v3
        with:
          ref: '1.19'

      - name: Redeem the sent Tag ğŸ·ï¸
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          TAG="${TAG#v}"
          echo "LATEST_TAG=$TAG" >> $GITHUB_ENV

      - name: Compressing texture from version 1.19ğŸ“¦ï¸
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.19.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Uploading the Texture 1.19ğŸ—ƒï¸
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          tag: "v${{ env.LATEST_TAG }}"
          name: "Dark Everywhere ${{ env.LATEST_TAG }}ğŸŒ™"
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}

  texturepack1_18:
    needs: texturepack1_19
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checking branch 1.18ğŸ”ï¸
        uses: actions/checkout@v3
        with:
          ref: '1.18'

      - name: Redeem the sent Tag ğŸ·ï¸
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          TAG="${TAG#v}"
          echo "LATEST_TAG=$TAG" >> $GITHUB_ENV
          
      - name: Compressing texture from version 1.18ğŸ“¦ï¸
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'Dark_Everywhere_1.18.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig *.md pack_hd.png'

      - name: Uploading the Texture 1.18ğŸ—ƒï¸
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          generateReleaseNotes: true
          tag: "v${{ env.LATEST_TAG }}"
          name: "Dark Everywhere ${{ env.LATEST_TAG }}ğŸŒ™"
          artifacts: "*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
